### ISSUE TITLE
[Feature Request] Implement From trait for i128 and u128

### ISSUE THREAD

**Issue by GrayJack** [Aatch/ramp#109]
Just for completeness sake :smile: 

Would it be as simple as putting `i128` in the `impl_from_prim!(signed   i8, i16, i32, i64, isize);` and `u128` in the `impl_from_prim!(unsigned u8, u16, u32, u64, usize);`?

**Comment by rozbb** [comment]
Thanks for the suggestion! This is now [available](https://docs.rs/ramp/0.5.1/ramp/int/struct.Int.html#impl-From%3Cu128%3E) in 0.5.1
