### ISSUE TITLE
Copy trait not implemented on Int struct

### ISSUE THREAD

**Issue by Antoxyde** [Aatch/ramp#110]
Is there any reason for this ?
It force to clone() everytime you need a for loop on range of Int, for example.

**Comment by Antoxyde** [comment]
Thanks for your explanation! I didn't see it that way.
I'm sorry if it was a n00b question.

**Comment by slinkydeveloper** [comment]
Hi @rozbb I'm n00b too and I just stumbled across this issue too :smile: The reason is that for a beginner it feels somehow unnatural to interact with numbers, which are usually primitive types, as heap allocated objects. Are you ok to add a little section in the readme that explains that?

**Comment by rozbb** [comment]
Maybe README isn't the appropriate place, but I can add a small mention of "Ints live on the heap" in the docs for the `Int` struct. Does that work?
