### ISSUE TITLE
could not find `AllocInit` in `alloc`

### ISSUE THREAD

**Issue by HaoXuan40404** [Aatch/ramp#121]
```rust
ramp version:0.5.6
rustc 1.40.0-nightly (e413dc36a 2019-10-14)
problem: could not find `AllocInit` in `alloc`
```

AllocInit is missed In this doc `https://doc.rust-lang.org/std/alloc/index.html, make me confused, how to enable nightly build

rustc 1.44.0-nightly (14b15521c 2020-04-23) doesn't have this problem

**Comment by rozbb** [comment]
`ramp` requires the latest version of nightly, since it uses the unstable `alloc` API

**Comment by HaoXuan40404** [comment]
> `ramp` requires the latest version of nightly, since it uses the unstable `alloc` API

Thanks
