### ISSUE TITLE
Cannot compile 0.5.6

### ISSUE THREAD

**Issue by jakasi2** [Aatch/ramp#122]
hi, I am using `rustc 1.45.0-nightly (7ced01a73 2020-04-30)` and when I try to build a simple program I am stuck at `ramp` compilation stage. I try to build with `cargo build --release`. I get the following error.

```
error[E0599]: no function or associated item named `empty` found for struct `std::ptr::Unique<_>` in the current scope
    --> C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\ramp-0.5.6\src\int.rs:3624:26
     |
3624 |             ptr: Unique::empty(),
     |                          ^^^^^ function or associated item not found in `std::ptr::Unique<_>`

```
What am I doing wrong? Thanks

**Comment by clarfon** [comment]
It was renamed to empty

**Comment by jakasi2** [comment]
Well probably, but this is the crate from crates.io. How can this be fixed so it would also work for others?

**Comment by jakasi2** [comment]
Issue was [updated](https://github.com/Aatch/ramp/commit/75e08835ec4e36c47a95fc63c417c7f036014db4) in 0.5.7 . It was because of Rust std::ptr interface change.

**Comment by rozbb** [comment]
Thanks for the report! Published on crates.io!
