### ISSUE TITLE
Junk in the cargo package source

### ISSUE THREAD

**Issue by bluss** [Aatch/ramp#18]
Ramp 0.1.6 has megabytes of junk files in the source directory. (perf.data and .ll files)

This is a reminder that cargo includes all non-ignored files in your working directory when you publish — look at `git status` before you publish.

(I downloaded all crates.io crates and I started to grep for junk)

**Comment by Aatch** [comment]
Oh, ouch. I wasn't aware of that. I should probably make a new release anyway, so I'll make sure to clean those up first.
