### ISSUE TITLE
Error compiling ramp 0.1.2

### ISSUE THREAD

**Issue by manfredlotz** [Aatch/ramp#3]
Hi there,
Compiling ramp gives:

   Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling ramp v0.1.2
/home/manfred/.cargo/registry/src/github.com-1ecc6299db9ec823/ramp-0.1.2/src/ll/limb.rs:52:9: 52:14 error: expected one of `extern`, `fn`, `type`, or `unsafe`, found `const`
/home/manfred/.cargo/registry/src/github.com-1ecc6299db9ec823/ramp-0.1.2/src/ll/limb.rs:52     pub const BITS : usize = 32;
                                                                                                   ^~~~~
Could not compile `ramp`.

To learn more, run the command again with --verbose.

**Comment by Aatch** [comment]
What compiler version are you using, as I can compile fine.

**Comment by manfredlotz** [comment]
% rustc -V
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
-- Manfred

**Comment by Aatch** [comment]
@manfredlotz well I'm not sure why you're getting that error in particular, but Ramp currently only works on the nightly compiler due to use of inline assembly (and a few other things, but that's the main one).

Closing since it compiles on a nightly.

**Comment by manfredlotz** [comment]
Yep, with a nightly built compiler compiling works fine.  Perhaps you should mention it in the README.md.

Thanks for looking into this.
