### ISSUE TITLE
 (2**64 - 1) * 2**64 + 2**64 == 1

### ISSUE THREAD

**Issue by huonw** [Aatch/ramp#45]
This test fails:

```rust
#[test]
fn foo() {
    let mut ar = ((Int::from(1) << 64) - 1) << 64_usize;
    let br = Int::from(1) << 64;
    assert_eq!(ar + br, Int::from(1) << 128);
}
```

(I'm debugging it now.)

**Comment by Aatch** [comment]
That is some edge case there. I'm guessing it's something to do with the shift-left implementation.

**Comment by huonw** [comment]
Seems like `ar` and `br` are computed correctly, but the number is normalised after doing the elementwise addition (i.e. `ll::add`), but before `push`ing the carry, so, in this case, the raw addition entirely overflows and leaves every limb 0 meaning normalization trims everything off. #46
