### ISSUE TITLE
ramp-0.2.2/src/ll/limb.rs:89:28: 89:66 error: unresolved name `std::intrinsics::u64_add_with_overflow` [E0425]

### ISSUE THREAD

**Issue by NobbZ** [Aatch/ramp#51]
rustc 1.6.0-nightly (5b4986fa5 2015-11-08)

**Comment by Aatch** [comment]
Ah, right, I need to push a new version. This has been fixed in master though.

**Comment by Aatch** [comment]
New version (0.2.3) just uploaded.
