### ISSUE TITLE
Possible latent memory corruption?

### ISSUE THREAD

**Issue by huonw** [Aatch/ramp#54]
https://travis-ci.org/Aatch/ramp/jobs/90644821 failed in the `cargo test --release` section:

```
---- sub::usize_int stdout ----

    thread 'sub::usize_int' panicked at '[quickcheck] TEST FAILED. Arguments: (3, BigIntStr("2"))', /home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/quickcheck-0.2.24/src/tester.rs:113

failures:

    sub::usize_int
```

But this isn't reliable (other test runs passed) and running `3 - Int::from(2)` in a test by itself works fine, suggesting memory corruption, in something (probably not `sub`).

**Comment by doomrobo** [comment]
I think I got something like that a few times. That should have been fixed [here](https://github.com/Aatch/ramp/pull/91/commits/f63f6bfb8247596d24bd91f2fae14126f560a916)
